# Generated by Django 4.0.5 on 2022-06-07 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_subject', models.CharField(max_length=100, verbose_name='Main subject you teach')),
                ('secondary_subject', models.CharField(max_length=100, verbose_name='Secound subject you teach')),
                ('availability', models.IntegerField(default=0, verbose_name='Working hours per week')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=200, verbose_name='Name and surname of your client')),
                ('info', models.TextField(blank=True, verbose_name='Usefull informations about client')),
                ('price', models.IntegerField(default=0)),
                ('starting_date', models.DateTimeField(help_text='%Y-%m-%d %H:%M', verbose_name='When the lesson begins')),
                ('end_date', models.DateTimeField(help_text='%Y-%m-%d %H:%M', verbose_name='When the lesson ends')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
