# Generated by Django 4.0.5 on 2022-06-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSProjekt', '0004_remove_tutor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='primary_subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Main subject you teach'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='secondary_subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secound subject you teach'),
        ),
    ]
