# Generated by Django 4.0.5 on 2022-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSProjekt', '0005_alter_tutor_primary_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='availability',
            field=models.IntegerField(blank=True, default=0, verbose_name='Working hours per week'),
        ),
    ]
